### ISSUE TITLE
peeking at the code

### ISSUE THREAD

**Issue by mnukka** [ThomasPe/WordPressUWP#5]
I would rename all "endpoint" variables to something like "wpSiteUrl" or is it standard way of describing something where client connects among C# coders? (serious question, since I don't write C# professionally)

Also WordpressCliet.ListPosts seems to be implementing unused parameters.

**Comment by ThomasPe** [comment]
Thanks for the great suggestions! 
There's no specific reason why I used "endpoint", this can very well be renamed.
I've already added some parameters to the ListPosts method that should / will be supported in the future - this whole project is still very much in the early stages.

**Comment by mnukka** [comment]
I have made few commits in my fork, if you should want to implement any of that, feel free to take a look and maybe get some ideas.

My gut feeling is that get and post functionality should be moved into different classes and make client inherit their functionality.

I also added some new properties to Post model because wordpress won't accept JSON if you try to create new posts where you have declared objects without all of their parameters. Example {"title":{"rendered:"a"}} without the "raw", it either takes {"title":"simple title"} or the whole deal. You might already know this, just sharing the knowledge since this WP REST API is quite new to me.

**Comment by ThomasPe** [comment]
Looking good! You are absolutely right about splitting up POST and GET functions.
I will also take a look at the new parameters - I'm new to the WP REST API as well!

**Comment by ThomasPe** [comment]
I've now included most of your suggestions, thank you! 
If you like you can resync and add additional changes as pull requests - perhaps for each change a small commit so I can check differences more easily and each change can be discussed separately.
Cheers!

**Comment by mnukka** [comment]
Yeah sorry about that, I should had created another branch instead of commiting to master
