### ISSUE TITLE
Unknown attachable member 'HtmlTools.HTML' on element 'webview'.

### ISSUE THREAD

**Issue by Javad-Alan** [ThomasPe/WordPressUWP#9]
Hi and tnx for this useful sample. I got this error on the first launch of the app and I'm sure I didn't mess with DetailPage.xaml ( wich is the host of error ) and also the referred class ( HtmlTools.cs ).

**Comment by ThomasPe** [comment]
Thanks, I'll be looking into it. This part will be removed anyway since I'm planning on using the UWP Community Toolkit for this.

**Comment by Javad-Alan** [comment]
Fixed it  ( just replaced the HTML part of the HtmlTools with Content )
` tools:HtmlTools.Content`
Thanks anyway 👍
